# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FGfD2o64ppTshq_mk9V8qc3NYZGNJjSL
"""

import requests
from bs4 import BeautifulSoup
import csv

# URL for OLX car cover search
url = "https://www.olx.in/items/q-car-cover"

# Set headers to mimic a real browser
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}

# Send HTTP request
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, 'html.parser')

# Find all listing containers
items = soup.find_all('li', class_='EIR5N')

# Open a file to save results
with open('car_cover_results.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['Title', 'Price'])

    for item in items:
        title_tag = item.find('span', class_='_2tW1I')
        price_tag = item.find('span', class_='_89yzn')

        title = title_tag.text.strip() if title_tag else 'N/A'
        price = price_tag.text.strip() if price_tag else 'N/A'

        writer.writerow([title, price])

print("Search results saved to car_cover_results.csv")